project_name: ss-test-goreleaser-windows

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/hello
    binary: hello
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - arm64

signs:
  - cmd: cosign
    artifacts: checksum
    signature: ${artifact}.sig
    certificate: ${artifact}.pem
    output: true
    env:
      - COSIGN_EXPERIMENTAL=1
    args:
      - sign-blob
      - --output-signature
      - ${signature}
      - --output-certificate
      - ${certificate}
      - --oidc-provider
      - github
      - ${artifact}

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'

chocolateys:
  - owners: Shunsuke Suzuki

    # The app's title.
    # A human-friendly title of the package.
    #
    # Default: ProjectName
    title: Test Chocolatey Package by GoReleaser

    # Your app's authors (probably you).
    authors: Shunsuke Suzuki

    # Your app's project url.
    # It is a required field.
    project_url: https://github.com/suzuki-shunsuke/goreleaser-windows-test

    # URL which is determined by the given Token (github,
    # gitlab or gitea).
    #
    # Default: depends on the git remote
    # Templates: allowed
    # url_template: "https://github.com/foo/bar/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    # App's icon.
    icon_url: https://github.com/suzuki-shunsuke.png

    # Your app's copyright details.
    copyright: 2023 Shunsuke Suzuki

    # App's license information url.
    license_url: https://github.com/suzuki-shunsuke/goreleaser-windows-test/blob/main/LICENSE

    # Your apps's require license acceptance:
    # Specify whether the client must prompt the consumer to accept the package
    # license before installing.
    require_license_acceptance: false

    # Your app's source url.
    project_source_url: https://github.com/suzuki-shunsuke/goreleaser-windows-test

    # Your app's documentation url.
    docs_url: https://github.com/suzuki-shunsuke/goreleaser-windows-test/blob/main/README.md

    # App's bugtracker url.
    bug_tracker_url: https://github.com/suzuki-shunsuke/goreleaser-windows-test/issues

    # Your app's tag list.
    tags: "goreleaser go test"

    # Your app's summary:
    summary: Test of Chocolatey Package by GoReleaser

    # This the description of your chocolatey package.
    # Supports markdown.
    description: |
      {{ .ProjectName }} is a test of releasing Chocolatey packages by GoReleaser.

    # Your app's release notes.
    # A description of the changes made in this release of the package.
    # Supports markdown. To prevent the need to continually update this field,
    # providing a URL to an external list of Release Notes is perfectly
    # acceptable.
    release_notes: "https://github.com/suzuki-shunsuke/goreleaser-windows-test/releases/tag/v{{ .Version }}"

    # App's dependencies
    # The version is not required.
    dependencies:
      - id: go
        version: 1.20.0

    # The api key that should be used to push to the chocolatey repository.
    #
    # WARNING: do not expose your api key in the configuration file!
    api_key: '{{ .Env.CHOCOLATEY_API_KEY }}'

    # The source repository that will push the package to.
    source_repo: "https://push.chocolatey.org/"

    # Setting this will prevent goreleaser to actually try to push the package
    # to chocolatey repository, leaving the responsibility of publishing it to
    # the user.
    skip_publish: false

    # GOAMD64 to specify which amd64 version to use if there are multiple
    # versions from the build section.
    #
    # Default: 'v1'
    # goamd64: v1
