project_name: ss-test-goreleaser-windows

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/hello
    binary: hello
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - arm64

signs:
  - cmd: cosign
    artifacts: checksum
    signature: ${artifact}.sig
    certificate: ${artifact}.pem
    output: true
    env:
      - COSIGN_EXPERIMENTAL=1
    args:
      - sign-blob
      - --output-signature
      - ${signature}
      - --output-certificate
      - ${certificate}
      - --oidc-provider
      - github
      - ${artifact}

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
