---
name: Release
on:
  push:
    tags: [v*]
jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write # required to create a release
      id-token: write # required for cosign
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: 1.21.1
          cache: true

      - uses: aquaproj/aqua-installer@36dc5833b04eb63f06e3bb818aa6b7a6e6db99a9 # v2.1.2
        with:
          aqua_version: v2.10.1

      - name: remove changes
        # Sometimes it is failed to release by goreleaser due to changes of go.sum
        run: git checkout -- .
      - name: fetch tags to release
        run: git fetch --tags -f
      - name: Unshallow
        run: git fetch --prune --unshallow
      - run: cosign version

      - name: Run GoReleaser
        run: goreleaser release --clean
        env:
          GITHUB_TOKEN: ${{ github.token }}
          CHOCOLATEY_API_KEY: ${{ secrets.CHOCOLATEY_API_KEY }}
